// design-sync pre-build for this repo (there is no library build to run).
// Usage: node .design-sync/build.mjs   (from the repo root)
//   1. compiles the site's Tailwind v4 stylesheet -> .design-sync/.cache/compiled.css
//   2. emits .d.ts for the synced components -> types/ (index.d.ts = the entry)
// Both outputs are gitignored and rebuilt on every sync.
import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

// 1. CSS
{
  const from = resolve(here, 'ds-styles.css');
  const to = resolve(here, '.cache/compiled.css');
  const css = readFileSync(from, 'utf8');
  const result = await postcss([tailwind({ base: root })]).process(css, { from, to });
  mkdirSync(dirname(to), { recursive: true });
  writeFileSync(to, result.css);
  console.error(`build: css -> ${to} (${(result.css.length / 1024).toFixed(0)} KB)`);
}

// 2. Types (tsc reports pre-existing app type errors such as window.gtag; declarations still emit)
{
  const typesDir = resolve(root, 'types');
  rmSync(typesDir, { recursive: true, force: true });
  const tsc = resolve(root, 'node_modules/typescript/bin/tsc');
  const r = spawnSync(process.execPath, [tsc, '-p', resolve(here, 'tsconfig.types.json')], { cwd: root, encoding: 'utf8' });
  const errs = (r.stdout + r.stderr).split('\n').filter((l) => /error TS/.test(l));
  if (errs.length) console.error(`build: tsc reported ${errs.length} type error(s) (declarations still emitted)`);
  // Re-export (not copy) the entry's declarations so its relative paths stay valid.
  writeFileSync(resolve(typesDir, 'index.d.ts'), "export * from './.design-sync/entry';\n");
  // The converter opens <repo>/index.d.ts (package.json has no "types" field).
  writeFileSync(resolve(root, 'index.d.ts'), "// generated by .design-sync/build.mjs for design-sync - not part of the app\nexport * from './types/index';\n");
  console.error(`build: types -> ${typesDir}/ (+ index.d.ts at the repo root)`);
}
